// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using scpmtf_app.Models;
//
//    var scpObject = ScpObject.FromJson(jsonString);

namespace scpmtf_app.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ScpObject
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("itemNo")]
        public string ItemNo { get; set; }

        [JsonProperty("objectClass")]
        public string ObjectClass { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("imageAttachment")]
        public string ImageAttachment { get; set; }
    }

    public partial class ScpObject
    {
        public static List<ScpObject> FromJson(string json) => JsonConvert.DeserializeObject<List<ScpObject>>(json, scpmtf_app.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<ScpObject> self) => JsonConvert.SerializeObject(self, scpmtf_app.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
